# Generated by Django 4.1.2 on 2024-07-30 21:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_assessmenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenthistory",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to=home.models.certificate_upload_path
            ),
        ),
    ]
