# Generated by Django 4.1.2 on 2024-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_assessmenthistory_score_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmenthistory",
            name="score_color",
            field=models.CharField(max_length=20),
        ),
    ]
