# Generated by Django 5.1.1 on 2024-09-11 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_assessmenthistory_score_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthistory',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
